insert into hr.ACCOUNT_TYPE (ACCOUNT_TYPE_ID , MNEMONIC ,ACCOUNT_TYPE_NAME ,CREATION_DATE) values(5001, 'MILES', 'Miles' ,'2020-01-01');
insert into hr.ACCOUNT_TYPE (ACCOUNT_TYPE_ID , MNEMONIC ,ACCOUNT_TYPE_NAME ,CREATION_DATE) values(5002, 'PLAY', 'Play' ,'2021-03-01');
